### ISSUE TITLE
new ES changes the media needed

### ISSUE THREAD

**Issue by Cissoubaka** [gfriloux/rompom#12]
in 5.24 we need
- screenshot,
- front box,
- wheel,
- video (maybe the normalized one)

**Comment by gfriloux** [comment]
I need XML data from `gamelist.xml` if possible.

**Comment by Cissoubaka** [comment]
exemple : 
```xml
<game>
		<path>./Castlevania - Portrait of Ruin (Europe) (En,Fr,De,Es,It).nds</path>
		<name>Castlevania - Portrait Of Ruin</name>
		<desc>Castlevania : Portrait of Ruin est un jeu d'action sur Nintendo DS. Vous incarnez Jonathan Morris et Charlotte Aulin, des amis d'enfance, qui décident d'aller bouter Brauner, un peintre vampire qui a pris possession des lieux et qui fait régner le chaos. A vous de déjouer ses plans en apprenant à vous servir du fouet légendaire de la famille Belmont.</desc>
		<image>./images/Castlevania - Portrait of Ruin (Europe) (En,Fr,De,Es,It)-image.png</image>
		<marquee>./images/Castlevania - Portrait of Ruin (Europe) (En,Fr,De,Es,It)-marquee.png</marquee>
		<thumbnail>./images/Castlevania - Portrait of Ruin (Europe) (En,Fr,De,Es,It)-thumb.png</thumbnail>
		<rating>0.9</rating>
		<releasedate>20070308T000000</releasedate>
		<developer>Konami</developer>
		<publisher>Konami</publisher>
		<genre></genre>
		<players>1-2</players>
	</game>
```
but there is some choice you can make in the UI of the scraper in batocera, so maybe there are more possibility

**Comment by gfriloux** [comment]
@Cissoubaka : ATM:
- `<thumbnail>` is `box3d`
- `<image>` is `mixrbv2`

Exemple of `<thumbnail>` : https://clone.screenscraper.fr/api2/mediaJeu.php?devid=xxx&devpassword=yyy&softname=zzz&ssid=test&sspassword=test&systemeid=1&jeuid=3&media=box-3D(asi)

Exemple of `<image>` : https://clone.screenscraper.fr/api2/mediaJeu.php?devid=xxx&devpassword=yyy&softname=zzz&ssid=test&sspassword=test&systemeid=1&jeuid=3&media=mixrbv2(eu)

You are asking for `Font Box`, and it seems it should change of one thoses.
Maybe `<image>` should become `Font Box` ?
Is that what you are asking?

**Comment by gfriloux** [comment]
what should be that xml tag for the wheel ? is that just `<wheel>`?

**Comment by gfriloux** [comment]
https://github.com/batocera-linux/batocera-emulationstation/blob/master/GAMELISTS.md

Does not list marquee or wheel tags

**Comment by Cissoubaka** [comment]
it's because there is some new gamelist display, grid, carousel, etc, and the media used by now are not eye friendly for those display mode.
